@startuml
title Systems Architecture
header <color blue> Blue: basic connection</color> \n <color red> Red: opeartion flow</color>

left to right direction

package AppElectron {
  package Frontend {
    usecase HomePage as "
      Frontend HomePage
      --
      app load homepage
      --
      project: electron
    "
    usecase SetIPPage as "
      Frontend SetIPPage
      --
      popup from menu
      --
      project: electron/out,
      build from project: electron-react
    "
  }

  usecase FrontendDB as "
    FrontendDB
    --
    localstroage
  "
}

package NetworArea {
  package ServicePCA {
    usecase TomcatA as "
      TomcatA
      --
      project: apache-tomcat-8.5.100
      project frontend: build from react
    "
  }

  package ServicePCB {
    usecase TomcatB
  }

  package ServicePCMore {
    usecase TomcatMore
  }
}

SetIPPage <--> FrontendDB#line:blue;text:blue : save and load IP
TomcatA ---> AppElectron#line:blue;text:blue : http://192.*.1
TomcatB ---> AppElectron#line:blue;text:blue : http://192.*.2
TomcatMore ---> AppElectron#line:blue;text:blue : http://192.*.more

HomePage --> HomePage#line:red;text:red : 1.select menu to show
HomePage --> SetIPPage#line:red;text:red : 2.popup to show to SetIPPage
SetIPPage --> TomcatA#line:red;text:red : 3.edit and select to visit http://192.*.1
HomePage <-- TomcatA#line:red;text:red : 4.load TomcatA page in FrontendB


@enduml