@startuml
title 上报与组网基本功能

participant MQ服务
participant 上级
participant 便携下级

== 现有机制 ==
loop 30s循环发送
便携下级 -> MQ服务: [20]推送本身网系与设备状态
note over 便携下级
{
    "all": false,				// 是否全员接收 必填
    "code": 20,				// 功能代码 必填
    "fromId": "147server",		// 发送方ID 必填
    "toId": "248server",		        // 接收方ID 必填 上级ID
    "timestamp": 1351561531000, // 时间戳 必填
    "data": {					// 交互数据 必填
        "jdMs": "147描述",			// 发送方描述 必填 随意
        "jdName": "147服务器",		// 发送方名称 必填
        "jdId": "147server",			// 发送方ID 必填
        "timestamp": 1351561531,		// 时间戳 必填
        "topology": {					// 网系结构 必填
            ...网系数据
        }
    }
}
endnote
上级 <- MQ服务: [11]拿到下级网系, 渲染更新下级网系数据
end loop

== 建议机制 ==
loop 30s循环发送 保持不动
便携下级 -> MQ服务: [20]推送本身网系与设备状态
note over 便携下级
{
    "all": false,				// 是否全员接收 必填
    "code": 20,				// 功能代码 必填
    "fromId": "147server",		// 发送方ID 必填
    "toId": "248server",		        // 接收方ID 必填 上级ID
    "timestamp": 1351561531000, // 时间戳 必填
    "data": {					// 交互数据 必填
        "jdMs": "147描述",			// 发送方描述 必填 随意
        "jdName": "147服务器",		// 发送方名称 必填
        "jdId": "147server",			// 发送方ID 必填
        "timestamp": 1351561531,		// 时间戳 必填
        "topology": {					// 网系结构 必填
            ...网系数据,
            增加下级IP,端口
        }
    }
}
endnote
上级 <- MQ服务: [11]拿到下级网系, 渲染更新下级网系数据
end loop

上级 -> 上级: 编辑便携下级网系
activate 上级
上级 -> 上级: 递归处理网系数据
上级 -> 便携下级: restful接口下级便携开放接口
    note over 便携下级
    新网系数据(可协助处理组织新网系数据函数)
    endnote
deactivate 上级

alt 成功
便携下级 -> 便携下级: 当前逻辑允许修改
便携下级 -> 上级: 修改成功
上级 -> 上级: 等待下一次 loop 推送网系, 会来新数据
else 失败
便携下级 -> 便携下级: 当前逻辑存在绿本内置逻辑冲突
    note over 便携下级
    可能的冲突:
    1. 便携本子正在操作该网系内设备
    2. 当前网系已过时(上级以为的当前网系 实际是MQ拿的30s前的数据, 实际便携设备网系已切换)
    3. 其他
    endnote
便携下级 -> 上级: 修改失败
上级 -> 上级: 弹窗提示修改失败
end
@enduml