@startuml
autonumber

participant 多级中心
participant MQ服务
participant 便携下级
participant 设备

== 下任务 ==
多级中心 -> MQ服务: [30]任务下发
MQ服务 -> 便携下级: [30]收到任务
便携下级 -> 便携下级: 根据任务拆解建立电磁环境任务
便携下级 -> MQ服务: [31]任务回执: 接受成功/拒绝?
多级中心 -> 多级中心: 任务变为待开始
便携下级 -> 便携下级: 前端接受socket刷新列表或提示跳转
便携下级 -> 便携下级: 点击开始
便携下级 <-> 设备: 下发给设备
便携下级 -> 多级中心: [31]任务回执: 开始/异常
loop
便携下级 <- 设备: 上数
end
便携下级 -> 便携下级: 人为结束任务
便携下级 -> 多级中心: [31]任务回执: 结束
便携下级 -> 多级中心: [32]上报最后的计算结果
@endmul
