@startuml
title "time picker"

participant Frontend
participant OtherFrontends


participant Backend

autonumber
Frontend -> Frontend: User at <color red>Timezone +1</color>, selects time Dec 13,
Frontend -> Frontend: Since we only to the day level, set the time to \n <color red> localtime: Dec 13 - 00:00:00</color>
Frontend -> Frontend: Transform the time to <color red> UTC: Dec 12 - 23:00:00 </color>
Frontend -> Backend: Send the time to the backend
Backend -> Backend: Store the time in the database


Backend -> Frontend: Send the UTC time back to the frontend <color red> UTC: Dec 12 - 23:00:00 </color>
Frontend -> Frontend: Transform to render: <color red> back to localtime: Dec 13 - 00:00:00</color>

Backend -> OtherFrontends: Send the UTC time <color red> UTC: Dec 12 - 23:00:00 </color>
note over OtherFrontends
  Other frontends will also get the UTC time,
  and will transform it to their local time:
  it could be:
  ...
  -2 -> Dec 12 - 21:00:00 -> begin at Dec - 12
  -1 -> Dec 12 - 22:00:00 -> begin at Dec - 12
  +0 -> Dec 12 - 23:00:00 -> begin at Dec - 12
  +1 -> Dec 13 - 00:00:00 -> begin at Dec - 13
  +2 -> Dec 13 - 01:00:00 -> begin at Dec - 13
  +3 -> Dec 13 - 02:00:00 -> begin at Dec - 13
  ...
end note
Backend -> OtherFrontends: All to local time to render

@enduml