@startuml
title payment view page development doc
legend right
  Operations:
  <color red> init </color>
  <color orange> paginate </color>
  <color green> filterQuery </color>
end legend

left to right direction

package Frontend-PaymentPage {
  package chartComponent
  package transactionComponent {
    usecase tableHeaderFilter
    usecase tableBody
    usecase pagination
  }
}

package hubPaymentStore {
  package actions {
    usecase getPaymentTransactions
    usecase getPaymentTransactionsPrevNext
    usecase getPaymentTransactionsQueryFilter
    ' usecase getPaymentTimeLine
    ' usecase getPaymentSpending
    ' usecase getPaymentIncome
    ' usecase getPaymentBalance
  }
  package state {
    usecase v2PaymentTransactions as "
      v2PaymentTransactions
      ---
      Table DataList from API
    "
    usecase v2PaymentTransactionsCursor as "
      v2PaymentTransactionsCursor
      ---
      Cursor from API, for pagination
    "
    usecase v2PaymentTransactionsUsersParams as "
      v2PaymentTransactionsUsersParams
      ---
      pageNumber
      ---
      for pagination, 'el-pagination' requires but not return from API
    "
    usecase v2PaymentTransactionsFilterQuery as "
      v2PaymentTransactionsFilterQuery
      ---
      for queryFilter
    "
  }
}

package Backend {
  usecase APITransactions as "
    /payment/transactions
    ---
    limit next prev, filterQuery. More...
  "
}


'初始渲染
getPaymentTransactions <--> APITransactions #line:red;text:red : 1.1 get init Data
getPaymentTransactions --> v2PaymentTransactions #line:red;text:red : 1.2.1 save to state
getPaymentTransactions --> v2PaymentTransactionsCursor #line:red;text:red : 1.2.2 save to state
v2PaymentTransactions --> tableBody  #line:red;text:red : 1.3.1 render Table Data
v2PaymentTransactionsCursor --> pagination  #line:red;text:red : 1.3.2 render pagination
v2PaymentTransactionsFilterQuery --> tableHeaderFilter  #line:red;text:red : 1.3.3 render filterQuery

'分页
pagination --> getPaymentTransactionsPrevNext #line:orange;text:orange : 2.1 get prev/next Data
getPaymentTransactionsPrevNext --> getPaymentTransactions #line:orange;text:orange : 2.2 get set pagination Data as param
getPaymentTransactions <--> v2PaymentTransactionsFilterQuery #line:orange;text:orange : 2.3 merge Data as param
getPaymentTransactions <--> APITransactions #line:orange;text:orange : 2.4 get Data, rest is same as <color red>1.2, 1.3</color>

'筛选渲染
tableHeaderFilter --> getPaymentTransactionsQueryFilter #line:green;text:green : 3.1 set filterQuery Data
getPaymentTransactionsQueryFilter --> v2PaymentTransactionsUsersParams #line:green;text:green : 3.2 reset to default value, pageNumber => 1
getPaymentTransactionsQueryFilter --> getPaymentTransactions #line:green;text:green : 3.3 get Data with Query as param
getPaymentTransactions --> APITransactions #line:green;text:green : 3.4 get Data, rest is same as <color red>1.2, 1.3</color>
@enduml