@startuml
title "update card in with Card Element in stripe"

box "Frontend"
participant CardComponent
end box

box "Backend"
participant requestService
end box

box Stripe
participant FrontendModule
participant BackendModule
participant StripeAPI
end box

note over FrontendModule
"https://js.stripe.com/v3/" or
"@stripe/stripe-js"
end note
note over BackendModule
require("stripe") in NodeJS
end note
@enduml