@startuml
title "email templates development flow(sendGrid)"

participant SendGrid
participant "Frontend template project" as Frontend
participant Backend

autonumber 1.1
== frontend: develop templates html file ==
Frontend -> Frontend: get the new design from Figma
Frontend -> Frontend: edit in dev mode and build to html file

== frontend: sync to SendGrid ==
alt "if the template is not in sendGrid"
  SendGrid -> SendGrid: create 2 templates for en/it html file
  SendGrid -> SendGrid: copy the templateId
  SendGrid -> Frontend: maintain the templateId and template relationship in the frontend project
  note over Frontend
    example:
    welcome: {
      backendRename<color red>?</color>: 'WELCOME_EMAIL', // it exits only for the old emails
      itSubject: 'Benvenuto in Aladia. Siamo felici di averti con noi.',
      itTemplate: 'templates/it/welcome/index.html',
      <color red>itSendGridTemplateId</color>: 'd-f1cf6445728d4d9abfc69ee11d6f2771',
      enSubject: 'Welcome to Aladia. We are glad to have you on board.',
      enTemplate: 'templates/en/welcome/index.html',
      <color red>enSendGridTemplateId</color>: 'd-9410f182daed4830b244dd283f7e1912',
      <color red>variables</color>: {
        fullName: 'Welcome Test Name',
        subject?: 'Welcome {{fullName}}' // if exists, it needs to set dynamic subject
        visitLink?: 'https://aladia.com/visit' // if exists, it shows the navigation link format
      },
    },
  end note
  Frontend -> Frontend: update in file <color red>/scripts/sendGrid/sendGridTemplateId.js</color>
end

Frontend -> SendGrid: sync the new template html file to sendGrid
Frontend -> Frontend: git commit [commit-x], git tag [tag-x], \n git push.


== backend: implement ==
autonumber 2.1
Frontend -> Backend: <color red>notify developer</color>: the templates on SendGrid and sendGridTemplateId.js file is updated, \n and ready for backend to use.
Backend <-> Frontend: developer check <color red>sendGridTemplateId.js</color> file to get the <color red>id</color>.
note over Backend
  example:
  WELCOME_EMAIL: { // free to rename the key
    templateName: 'welcome', // free to edit the value, but it's better to follow the frontend project template name
    <color red>templateId_en</color>: 'd-9410f182daed4830b244dd283f7e1912',
    <color red>templateId_it</color>: 'd-f1cf6445728d4d9abfc69ee11d6f2771',
    subject: 'Welcome to Aladia. We are glad to have you on board.',  // free to edit the value
    it_subject: 'Benvenuto in Aladia. Siamo felici di averti con noi.',  // free to edit the value
  },

<color red>Backend developer could edit the text I said `free to rename/edit`, but its better to follow from the frontend project for better match.</color>
end note
Backend -> Backend: update the id in \n <color red>src/microservices/notification/mail/type/email-template.type.ts</color>
Backend <-> Frontend: developer check <color red>sendGridTemplateId.js</color> file to get the <color red>variables</color>.
Backend <-> SendGrid: login sendGrid, <color red>double check the variables</color> in the html file.
Backend -> Backend: update the variables in \n <color red>src/common/.../xxx.dto.ts toMailPlaceholders</color>
Backend -> Backend: test
@enduml