@startuml
title "branch flow and task status"
legend top right
  <color green>Operator </color>
  <color blue>ClickUp status update </color>
end legend


box "Deployed branches"
participant prod
participant staging
participant develop
end box

box "development branches"
participant TaskBranch as "Task branch"
participant SubtaskBranch as "Subtask branch"
end box

autonumber
prod -> TaskBranch: create branch from production
note over TaskBranch
  clickup status: <color blue> In progress </color>
  Operator: <color green>developer</color>
  update manually
end note
TaskBranch -> TaskBranch: develop and test on task branch, \n local env
TaskBranch -> TaskBranch: ready to merge
  autonumber 4.1
  alt "PR to develop"
    TaskBranch -> develop: create PR to develop branch 
    note over TaskBranch
      clickup status: <color blue> Supervisioning </color>
      Operator: <color green>developer</color>
      update by PR title
    end note
    develop -> develop: <color black>Approve access</color> => reviewer with write access.
    develop -> develop: merged
    develop -> develop: Dev team testing
  end
  autonumber 5.1
  alt if "find bug on https://develop.aladia.io"
    TaskBranch -> SubtaskBranch: create subtask branch from task branch
    note over TaskBranch
      clickup status: <color blue> Fixing </color>
      Operator: <color green>developer</color>
      update manually
    end note    
    SubtaskBranch -> SubtaskBranch: develop and test on subtask branch
    SubtaskBranch -> TaskBranch: PR merge back to mainTaskBranch
    TaskBranch -> develop: same flow <b>back from Step 4.1</b>
  end

' pr to staging
== staging ==
autonumber 6
develop -> develop: develop env OK, PR to staging, 
autonumber 7.1
  alt "PR to staging"
    TaskBranch -> staging: create PR to staging branch 
    note over TaskBranch
      clickup status: <color blue> Staging </color>
      Operator: <color green>developer</color>
      update by PR title
    end note
    staging -> staging: <color black>Approve access</color> => reviewer with write access.
    staging -> staging: merged
    staging -> staging: QA team testing
  end
  autonumber 8.1
  alt if "find bug on https://staging.aladia.io"
    note over TaskBranch
      clickup status: <color blue> Fixing </color>
      Operator: <color green>QA</color>
      update manually
    end note    
    TaskBranch -> SubtaskBranch: create subtask branch from task branch  
    SubtaskBranch -> SubtaskBranch: develop and test on subtask branch
    SubtaskBranch -> TaskBranch: PR merge back to mainTaskBranch
    TaskBranch -> TaskBranch: <b>back from Step 4.1</b>, merge develop first
  else "else 'testing on staging passed'"
    note over staging
      Operator: <color green>QA</color>
    end note  
    staging -> prod: create PR to prod
    alt if "auto test failed in PR checking"
      note over staging
        clickup status: <color blue> Test Failed </color>
        Operator: <color green>QA</color>
        update manually
      end note  
      staging -> TaskBranch: similar flow from <b>Step 8.1</b>, but keep the `Test Failed` status.
    else "else 'auto test passed'"
      note over staging
        Operator: <color blue>Closed</color>
        Operator: <color green>QA</color>
        update manually
      end note  
      staging -> prod: merged
      TaskBranch -> TaskBranch: delete TaskBranch, who will do it?
    end
  end
@enduml