@startuml
participant 便携设备
participant 转换服务
participant 416设备

便携设备 -> 转换服务: 416A频段扫描下发指令

activate 转换服务
转换服务 -[#Green]> 转换服务: 416A频段扫描下发指令 解码
转换服务 -[#Green]> 转换服务: 找到对应的416映射功能->416频段扫描 
转换服务 -[#Red]> 转换服务: 416A->416频段扫描参数转化
转换服务 -[#Orange]> 转换服务: 416频段扫描下发指令 编码
转换服务 -> 416设备: 416频段扫描下发指令
deactivate 转换服务

alt 多包重复
转换服务 <- 416设备: 416频段扫描结果
activate 转换服务
转换服务 -[#Orange]> 转换服务: 416频段扫描结果 解码
转换服务 -[#Red]> 转换服务: 416->416A频段扫描结果转化 
转换服务 -[#Red]> 转换服务: 416A频段扫描结果 编码 
便携设备 <- 转换服务: 416A频段扫描结果
deactivate 转换服务
end

便携设备 -> 转换服务: 416A频段扫描结束指令

activate 转换服务
转换服务 -[#Green]> 转换服务: 416A频段扫描结束指令 解码
转换服务 -[#Green]> 转换服务: 找到对应的416映射功能->416频段扫描 
转换服务 -[#Orange]> 转换服务: 416频段扫描结束指令 编码
转换服务 -> 416设备: 416频段扫描结束指令
deactivate 转换服务

416设备 -> 416设备: 结束
@enduml

解码: 二进制 -> 可读
解码: 编码 -> 二进制
红色: 完全不具备
橘色: 具备部分
绿色: 已经具备