@startuml
autonumber

participant 多级中心
participant MQ服务
participant 便携下级

== 初始化 ==
多级中心 -> 多级中心: 启动
多级中心 -> MQ服务: [10]通知分区上报

便携下级 -> 便携下级: 启动
便携下级 -> MQ服务: [12]上报唯一标识和关系([11]中拿)
便携下级 -> MQ服务: [13]拉取最新关系
便携下级 -> 便携下级: 更改网系/更改标识
loop 30s
便携下级 -> MQ服务: [20]推送本身网系与设备状态
end loop

== 组网 ==
多级中心 -> 多级中心: 拿到必要信息组网, 保存
多级中心 -> MQ服务: [11]推送上下级网关系
MQ服务 -> 便携下级: [11]拿到上下级网关系
便携下级 -> 便携下级: 内存中存上下级网关系

== 组网更新? ==
便携下级 -> 便携下级: 修改自身
便携下级 -> MQ服务: [14]向所有分区发送信息变更通知
MQ服务 -> 便携下级: [14]更新网系
MQ服务 -> 多级中心: [14]更新网系

== 通知上报交互? ==
多级中心 -> MQ服务: [10]通知分区上报
MQ服务 -> 便携下级: [10]接受分区上报
便携下级 -> MQ服务: [12]上报唯一标识和关系([11]中拿)

== 拉取最新关系? ==
便携下级 -> MQ服务: [13]拉取最新关系
MQ服务 -> 多级中心: [13]接受拉取最新关系
MQ服务 -> 便携下级: [13]接受拉取最新关系
便携下级 -> MQ服务: [12]上报唯一标识和关系([11]中拿)
@endmul
