@startuml
title 上报与组网基本功能
autonumber

participant 多级配网中心
participant MQ服务
participant 上级
participant 便携下级

便携下级 -> 便携下级: 启动/更改网系
便携下级 -> MQ服务: [12], 没有指向id
note over 便携下级
{
    "all": false,   					// 是否全员接收 必填
    "code": 12,					// 各分区上报给“多级监测网络配置中心”的信息 必填
    "fromId": "147server",			// 发送方ID标识 必填
	"timestamp": 1351561531000,	// 时间戳 必填
    "data": {
        "jdMs": "147描述",			// 节点描述 随意必填
        "jdName": "147服务器",		// 节点名称 必填
        "jdId": "147server",		// 节点ID 必填
		"ptlb": "平台类别",				// 平台类别
		"timestamp": 13515615313000,	// 接收更新关系时 的时间戳，没有时可=0 必填
        "gx": [							// 无关系时可空  nil or [] ?
            {...}
        ]
    }
}
endnote

多级配网中心 <- MQ服务: pull 获取
多级配网中心 -> 多级配网中心: 组网
多级配网中心 -> MQ服务: [11]推送上下级网关系
note over 多级配网中心
{
    "all": true,					// 是否全员接收(分区主动查询关系时为false)
    "code": 11,					// 功能代码
	"timestamp": 1351561531000,	// 时间戳
    "toId": "248server",			// 接收方ID(分区主动查询关系时才有值)
    "data": [{						// 交互数据
        "jdMs": "248描述",			// 节点描述
        "jdName": "248服务器",		// 节点名称
        "jdId": "248server",				// 节点编号
        "ptlb": "平台类别",				// 平台类别
        "children": [{...}]
    }]
}
endnote
上级 <- MQ服务: [11]拿到带网系的上级
上级 -> 上级: 渲染显示

便携下级 <- MQ服务: [11]拿到带网系的上级
便携下级 -> 便携下级: 存内存, 开启loop
loop 30s
便携下级 -> MQ服务: [20]推送本身网系与设备状态
note over 便携下级
{
    "all": false,				// 是否全员接收 必填
    "code": 20,				// 功能代码 必填
    "fromId": "147server",		// 发送方ID 必填
    "toId": "248server",		        // 接收方ID 必填 上级ID
    "timestamp": 1351561531000, // 时间戳 必填
    "data": {					// 交互数据 必填
        "jdMs": "147描述",			// 发送方描述 必填 随意
        "jdName": "147服务器",		// 发送方名称 必填
        "jdId": "147server",			// 发送方ID 必填
        "timestamp": 1351561531,		// 时间戳 必填
        "topology": {					// 网系结构 必填
            "jdbh": "147server",	    	// 网系ID（为当前节点ID）, 保证唯一 (作为上级站的渲染key)
            "jdmc": "147服务器",    		// 网系名称（为当前节点名称）,
            "jdlx": "wx",			    // 节点类型
            "children": [{							// 中心站
                "jdbh": "ZX_FD_0003",			// 中心站编号
                "jdmc": "147中心站",			// 中心站名称,
                "jdlx": "zx",					// 节点类型
                "parentjdbh": "147server",		// 父节点编号
                "parentName": "147服务器",	// 父节点名称
                "bz":"备注",					// 备注
                "children": [{				// 监测站
                    "jdbh": "mn-xh",			// 监测站编号
                    ...,
                    "txxy": "LHPPGL2021",		// 通信协议编码(416a)
                    "children": [{		// 设备
                        "jdbh": "JD00000081",	// 设备编号
                        ...
                        "bz":"备注"				// 备注
                    }]
                }]
            }]
        }
    }
}
endnote
上级 <- MQ服务: [11]拿到下级网系, 渲染更新下级网系数据
end loop
@enduml