@startuml
left to right direction
package 页面 {
    package functions {
        usecase init页面 as "
            init页面
            ---
            get页面JSON,
            get数据JSON
        " 
        usecase submitFunc as "
            submitFunc
            ---
            post脚本
        "
        usecase 提交btn as "
            提交btn
            ---
            遍历当前页面所有的 input_key + value,
            post数据JSON
        "
    }

    package components {
        package input {
            usecase inputOnchange
            usecase inputValue
        }
        package select {
            usecase selectOnchange
            usecase selectValue
        }
    }
    
}

package Restful {
    usecase get数据JSON as "
    get数据JSON
    ---
    get组件项接口
    get组件项-value接口
    "
    usecase post数据JSON
    usecase post脚本
}

package zmq {
    usecase inputZMQ
    usecase selectZMQ
}

init页面 <-- get数据JSON #red : 1获取页面初始数据
init页面 --> inputValue #red : 2 从JSON拿value渲染
inputOnchange --> submitFunc #red : 3.1加入单位转换 + newValue, 调用父级回调
submitFunc --> post数据JSON #red : 3.1提交变动到数据库
submitFunc --> post脚本 #red: 4.脚本

post脚本 --> zmq #red : 5.c#计算
selectZMQ --> selectValue #red : 6.zmq pub 订阅 推送变化 新value

提交btn <-- components #red : 7.1 遍历获取子组件val
提交btn --> post数据JSON #red : 7.2 提交更新db
@enduml